---
version: '3.8'
services:
  db:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3332:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
