---
version: '3.8'
services:
  portfolio-apis-postgres:
    container_name: portfolio-apis-postgres
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3332:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
